module ApplicationHelper
    
    def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
end

 def us_cities
    [
      ['New York', 'AL'],
      ['Los Angeles', 'AK'],
      ['Chicago', 'AZ'],
      ['Houston', 'AR'],
      ['Philadelphia[', 'CA'],
      ['Phoenix', 'CO'],
      ['San Antonio', 'CT'],
      ['San Diego', 'DE'],
      ['Dallas of Columbia', 'DC'],
      ['San Jose', 'FL'],
      ['Austin', 'GA'],
      ['Jacksonville', 'HI'],
      ['San Francisco', 'ID'],
      ['Indianapolis', 'IL'],
      ['Columbus', 'IN'],
      ['Fort Worth', 'IA'],
      ['Charlotte', 'KS'],
      ['Seattle', 'KY'],
      ['Denver', 'LA'],
      ['El Paso', 'ME'],
      ['Detroit', 'MD'],
      ['Washington', 'MA'],
      ['Boston', 'MI'],
      ['Memphis', 'MN'],
      ['Nashville', 'MS'],
      ['Portland', 'MO'],
      ['Oklahoma City', 'MT'],
      ['Las Vegas', 'NE'],
      ['Baltimore', 'NV'],
      ['Louisville', 'NH'],
      ['Milwaukee', 'NJ'],
      ['Albuquerque', 'NM'],
      ['Tucson', 'NY'],
      ['Fresno', 'NC'],
      ['Sacramento', 'ND'],
      ['Kansas City', 'OH'],
      ['Long Beach', 'OK'],
      ['Mesa', 'OR'],
      ['Atlanta', 'PA'],
      ['Colorado Springs', 'PR'],
      ['Virginia Beach', 'RI'],
      ['Raleigh', 'SC'],
      ['Omaha', 'SD'],
      ['Miami', 'TN'],
      ['Oakland', 'TX'],
      ['Minneapolis', 'UT'],
      ['Tulsa', 'VT'],
      ['Wichita', 'VA'],
      ['New Orleans', 'WA'],
      ['Arlington', 'WV'],
      ['Cleveland', 'WI'],
      ['Bakersfield', 'WY']
    ]
end
end
